### ISSUE TITLE
Bug when calling DAO webservice from R package

### ISSUE THREAD

**Issue by fbastian** [BgeeDB/bgee_apps#132]
In GitLab by @fbastian on Jun 21, 2016, 12:22

Following the bug report: 

    Building URLs to retrieve organ relationships from Bgee.........
        URL successfully built 
    (http://r.bgee.org/?page=dao&action=org.bgee.model.dao.api.ontologycommon.RelationDAO.getAnatEntityRelations&display_type=tsv&species_list=10090&attr_list=SOURCE_ID&attr_list=TARGET_ID)
        Submitting URL to Bgee webservice (can be long)
       trying URL 
    'http://r.bgee.org/?page=dao&action=org.bgee.model.dao.api.ontologycommon.RelationDAO.getAnatEntityRelations&display_type=tsv&species_list=10090&attr_list=SOURCE_ID&attr_list=TARGET_ID'
    Content type 'text/tab-separated-values;charset=UTF-8' length 0 bytes
    
    downloaded 0 bytes

    Error in read.table(paste0(pathToData, organRelationshipsFileName, ".tmp"),  :
       no lines available in input

Looking at the log on the server: 

    [ajp-bio-8009-exec-8] ERROR org.bgee.controller.FrontController 215 doRequest - catching java.lang.StringIndexOutOfBoundsException
        at java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:733)
        at java.lang.StringBuilder.delete(StringBuilder.java:244)
        at org.supercsv.encoder.DefaultCsvEncoder.encode(DefaultCsvEncoder.java:42)
        at org.supercsv.io.AbstractCsvWriter.escapeString(AbstractCsvWriter.java:102)
        at org.supercsv.io.AbstractCsvWriter.writeRow(AbstractCsvWriter.java:196)
        at org.supercsv.io.AbstractCsvWriter.writeHeader(AbstractCsvWriter.java:228)
        at org.bgee.view.csv.CsvDAODisplay.displayTOs(CsvDAODisplay.java:46)
        at org.bgee.controller.CommandDAO.processGetAnatEntitiyRelations(CommandDAO.java:296)
        at org.bgee.controller.CommandDAO.processRequest(CommandDAO.java:90)
        at org.bgee.controller.FrontController.doRequest(FrontController.java:211)
        at org.bgee.controller.FrontController.doGet(FrontController.java:267)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at net.sf.ehcache.constructs.web.filter.GzipFilter.doFilter(GzipFilter.java:95)
        at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

It is related to a bug in `supercsv` (cf. https://sourceforge.net/p/supercsv/bugs/43/) fixed in release 2.2.1 (cf. http://super-csv.github.io/super-csv/release_notes.html#a2.2.1). Needs to update supercsv.

**Comment by fbastian** [comment]
In GitLab by @fbastian on Jun 21, 2016, 13:19

Fixed in 0d85c0253
